apiVersion: v1
data:
  initdb.sql: "CREATE DATABASE sample;\nCREATE TABLE info (\n\tid SERIAL PRIMARY KEY,\n\tAge
    INT,\n\tEmail TEXT UNIQUE NOT NULL,\n\tFirstname TEXT,\n\tLastname TEXT\n);\nINSERT
    INTO info (Age, Email, Firstname, Lastname) VALUES\n(20,'test1@example.com','Mario','Bross'),\n(23,'test2@example.com','Angela','Haski'),\n(40,'test3@example.com','Andrew','Soul'),\n(21,'test4@example.com','Mico','Hikik'),\n(51,'test5@example.com','Angel','Sadin'),\n(70,'test6@example.com','Mark','Austin'),\n(32,'test7@example.com','Sophie','Deny'),\n(45,'test8@example.com','Sarah','Fiderst');\n\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: initdb-cm-sql
---
apiVersion: batch/v1
kind: Job
metadata:
  name: initdb
spec:
  completions: 1
  template:
    metadata:
      name:  initdb
      labels:
        app: init
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - image: "postgres:10.1" 
        name: initialize
        command: 
        - /bin/sh
        - -c 
        - |
            sleep 30
            export PGPASSWORD=$POSTGRES_PASSWORD
            psql -U $POSTGRES_USER -h $DB_HOST -d $POSTGRES_DB -f /load/initdb.sql
            exit 0
        volumeMounts:
        - name: sqlinit
          mountPath: /load
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_HOST
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_DB
      restartPolicy: Never  
      volumes:
        - name: sqlinit
          configMap:
            name: initdb-cm-sql

