apiVersion: v1
data:
  DB_HOST: ZGItc3Zj
  DB_PASSWORD: aW5pdDEyMzQ=
  DB_PORT: NTQzMg==
  DB_USER: YXBw
  DB_TABLE: aW5mbwo=
  POSTGRES_DB: c2FtcGxl
  POSTGRES_PASSWORD: aW5pdDEyMzQ=
  POSTGRES_USER: cG9zdGdyZXM=
kind: Secret
metadata:
  creationTimestamp: null
  name: db-secret
