apiVersion: v1
data:
  initdb.sql: "CREATE DATABASE sample;\nCREATE TABLE info (\n\tid SERIAL PRIMARY KEY,\n\tAge
    INT,\n\tEmail TEXT UNIQUE NOT NULL,\n\tFirstname TEXT,\n\tLastname TEXT\n);\nINSERT
    INTO info (Age, Email, Firstname, Lastname) VALUES\n(20,'test1@example.com','Mario','Bross'),\n(23,'test2@example.com','Angela','Haski'),\n(40,'test3@example.com','Andrew','Soul'),\n(21,'test4@example.com','Mico','Hikik'),\n(51,'test5@example.com','Angel','Sadin'),\n(70,'test6@example.com','Mark','Austin'),\n(32,'test7@example.com','Sophie','Deny'),\n(45,'test8@example.com','Sarah','Fiderst');\n\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: initdb-cm-sql
