apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: postgres-pv-claim
  labels:
    app: fullstack-postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 5Gi
