apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv-volume
  labels:
    type: local
    app: db
spec:
  storageClassName: local-path
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: db-pv-claim
  labels:
    app: db
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 5Gi
